return {
  { lhs = "<Plug>(gh-pr-open)", rhs = "<Cmd>GhPrOpen<CR>", desc = "Open PR tree" },
  { lhs = "<Plug>(gh-pr-list)", rhs = "<Cmd>GhPrList<CR>", desc = "List PRs (Telescope)" },
  { lhs = "<Plug>(gh-pr-comments)", rhs = "<Cmd>GhPrComments<CR>", desc = "Open PR comments tree" },
  { lhs = "<Plug>(gh-pr-start-review)", rhs = "<Cmd>GhPrStartReview<CR>", desc = "Start PR review flow" },
  { lhs = "<Plug>(gh-pr-refresh)", rhs = "<Cmd>GhPrRefresh<CR>", desc = "Refresh PR data" },
  { lhs = "<Plug>(gh-pr-review-refresh)", rhs = "<Cmd>GhPrReviewRefresh<CR>", desc = "Force refresh PR Review data" },
  { lhs = "<Plug>(gh-pr-overview)", rhs = "<Cmd>GhPrOverview<CR>", desc = "Open PR overview" },
  { lhs = "<Plug>(gh-pr-overview-refresh)", rhs = "<Cmd>GhPrOverviewRefresh<CR>", desc = "Refresh PR overview" },
  { lhs = "<Plug>(gh-pr-checkout)", rhs = "<Cmd>GhPrCheckout<CR>", desc = "Checkout PR" },
  { lhs = "<Plug>(gh-pr-open-diff)", rhs = "<Cmd>GhPrOpenDiff<CR>", desc = "Open PR file diff" },
  { lhs = "<Plug>(gh-pr-open-original)", rhs = "<Cmd>GhPrOpenOriginal<CR>", desc = "Open PR file base version" },
  { lhs = "<Plug>(gh-pr-open-modified)", rhs = "<Cmd>GhPrOpenModified<CR>", desc = "Open PR file head version" },
  { lhs = "<Plug>(gh-pr-open-commit-patch)", rhs = "<Cmd>GhPrOpenCommitPatch<CR>", desc = "Open selected commit patch" },
  { lhs = "<Plug>(gh-pr-review-tree)", rhs = "<Cmd>GhPrReviewTree<CR>", desc = "Toggle PR Review source" },
  { lhs = "<Plug>(gh-pr-my-pr)", rhs = "<Cmd>GhPrMyPr<CR>", desc = "Toggle My PR source" },
  { lhs = "<Plug>(gh-pr-toggle-reviewed)", rhs = "<Cmd>GhPrToggleReviewed<CR>", desc = "Toggle viewed" },
  { lhs = "<Plug>(gh-pr-next-change)", rhs = "<Cmd>GhPrNextChange<CR>", desc = "Next diff change" },
  { lhs = "<Plug>(gh-pr-prev-change)", rhs = "<Cmd>GhPrPrevChange<CR>", desc = "Previous diff change" },
  { lhs = "<Plug>(gh-pr-toggle-changes-panel)", rhs = "<Cmd>GhPrToggleChangesPanel<CR>", desc = "Toggle diff changes panel" },
  { lhs = "<Plug>(gh-pr-approve)", rhs = "<Cmd>GhPrApprove<CR>", desc = "Approve active PR" },
  { lhs = "<Plug>(gh-pr-request-changes)", rhs = "<Cmd>GhPrRequestChanges<CR>", desc = "Request changes on active PR" },
  { lhs = "<Plug>(gh-pr-comment)", rhs = "<Cmd>GhPrComment<CR>", desc = "Comment on active PR" },
  { lhs = "<Plug>(gh-pr-review-submit)", rhs = "<Cmd>GhPrReviewSubmit<CR>", desc = "Submit pending review as comment" },
  { lhs = "<Plug>(gh-pr-review-approve)", rhs = "<Cmd>GhPrReviewApprove<CR>", desc = "Submit pending review as approve" },
  {
    lhs = "<Plug>(gh-pr-review-request-changes)",
    rhs = "<Cmd>GhPrReviewRequestChanges<CR>",
    desc = "Submit pending review as request changes",
  },
  { lhs = "<Plug>(gh-pr-review-discard)", rhs = "<Cmd>GhPrReviewDiscard<CR>", desc = "Discard pending review" },
  { lhs = "<Plug>(gh-pr-merge)", rhs = "<Cmd>GhPrMerge<CR>", desc = "Merge active PR" },
}
